[workspace]
resolver = "3"
members = ["sonata-server"]

[workspace.package]
version = "0.1.0"
authors = ["Suya1671 <suyashtnt@gmail.com>"]
license = "MIT"
edition = "2024"

[workspace.lints.clippy]
pedantic = "warn"
nursery = "warn"
cargo = "warn"
