[package]
name = "sonata-server"
description = "A music server designed to take advantage of Musicbrainz tagging."
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
